### ISSUE TITLE
Broken handling of unicode f literals

### ISSUE THREAD

**Issue by tlotze** [asottile/tokenize-rt#130]
When applying `pyupgrade` to code like this: `u'foo: {}'.format(1)`, things break when using `tokenize-rt`, version 5: the outcome is `fu'foo: {1}'`, which is an invalid literal. Earlier versions work fine and the effect is independent of the `pyupgrade` version (tested with 3.2.2 and 2.38.2).

**Comment by asottile** [comment]
garbage in garbage out -- pyupgrade only supports python 3.x code

**Comment by asottile** [comment]
oh but actually this is still valid 3.x code -- please open an issue on `pyupgrade` instead -- this isn't a `tokenize-rt` problem

**Comment by asottile** [comment]
actually was easy enough to just fix https://github.com/asottile/pyupgrade/pull/762

**Comment by tlotze** [comment]
Cool, thank you!
