### ISSUE TITLE
Missing py.typed

### ISSUE THREAD

**Issue by christianbundy** [asottile/tokenize-rt#147]
It looks like tokenize-rt has type annotations, but since it doesn't package `py.typed` then type checkers won't use these type annotations and [generally] just infer everything as `Any`. Would you be open to a PR that adds `py.typed` to the repo?

**Comment by asottile** [comment]
it can't.  pep 561 does not support single-file distributions

**Comment by christianbundy** [comment]
Sure, but we could have a multi-file distribution. Do you want `py.typed` or not really? If you're open to it then we can add it (and remove some type ignores for library users), but if you don't want it then that's cool too. Mostly just don't want to waste any of our time talking about distribution configs if that's not the root blocker.

**Comment by asottile** [comment]
I have closed the issue so you know my answer

**Comment by christianbundy** [comment]
> Explicit is better than implicit.

**Comment by asottile** [comment]
yes that's why I explicitly closed the issue
